const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const createColors = require('../src/domains/colors/color-library.service');
const createParser = require('../src/domains/twitch/twitch-color-directive');
const createRouting = require('../src/domains/twitch/twitch-light-routing');
const createServer = require('../src/app/core/create-core-server');
function setup(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'twitch-light-program-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const colorLibrary = createColors({ storePath: path.join(root, 'colors.json'), seedCustomColors: { red: '#123456' }, fuzzyMinScore: 180 });
  const storePath = path.join(root, 'routing.json');
  const routing = createRouting({ storePath, colorLibrary });
  const parser = createParser({ colorLibrary, getParserOptions: routing.parserOptions });
  return { root, colorLibrary, routing, parser, storePath };
}
const rule = (id, prefix, fixtureIds, enabled = true) => ({ id, name: id, prefix, fixtureIds, enabled });
test('descriptors and brightness are deterministic and request-local, with canonical bare base colors', t => {
  const { parser } = setup(t);
  const parse = text => parser.parseTwitchColorDirective(text);
  const red = parse('red');
  assert.equal(red.hex, '#ff0000');
  assert.equal(parse('light red').hex, '#ff5959');
  assert.equal(parse('pastel red').hex, '#ff9999');
  assert.equal(parse('dark blue').hex, '#00008c');
  assert.equal(parse('dark blue').brightnessPercent, 55);
  assert.equal(parse('blue 25%').wizState.dimming, 25);
  assert.equal(parse('25%').type, 'brightness_only');
  assert.equal(parse('muted blue').hex, '#2222bb');
  assert.deepEqual(parse('red'), red);
  assert.deepEqual(parse('bright red').modifiers, {});
  assert.equal(parse('red').brightnessPercent, 100);
  assert.equal(parse('LIGHT BLEU').ok, true);
  assert.equal(parse('LIGHT BLEU').modifiers.tone, 'light');
  for (const input of ['light dark red', 'muted vivid blue', 'warm cool white', 'red 101%', 'red 0%', 'red 20% 60%', 'dark', 'x'.repeat(97)]) assert.equal(parse(input).ok, false, input);
  assert.doesNotThrow(() => parse('constructor red'));
});
test('routing enforces exclusive fixture ownership, persists edits, and avoids startup writes', t => {
  const { routing, storePath, colorLibrary } = setup(t);
  assert.equal(fs.existsSync(storePath), false);
  assert.equal(routing.save({ ...routing.snapshot(), mode: 'assignments', rules: [rule('a', '', ['left']), rule('b', 'desk', ['left'])] }).error, 'fixture_has_multiple_twitch_owners');
  assert.equal(routing.save({ ...routing.snapshot(), mode: 'assignments', rules: [rule('a', '', ['left']), rule('b', '', ['right'])] }).error, 'multiple_active_fixture_rules');
  const state = routing.save({ ...routing.snapshot(), mode: 'assignments', rules: [rule('active-fixtures', '', ['left', 'right']), rule('c', 'desk', ['desk']), rule('empty', 'stage', [])] });
  assert.equal(state.ok, true);
  assert.deepEqual(routing.resolve('red').fixtureIds, ['left', 'right']);
  assert.deepEqual(routing.resolve('DESK: light red').fixtureIds, ['desk']);
  assert.deepEqual(routing.resolveAll().fixtureIds, ['left', 'right', 'desk']);
  assert.deepEqual(routing.resolveGroup('c').fixtureIds, ['desk']);
  assert.equal(routing.resolve('DESK: light red').text, 'light red');
  assert.equal(routing.save({ ...state, rules: [rule('a', 'red', ['left'])] }).error, 'prefix_conflicts_with_color_language');
  assert.equal(routing.save({ ...state, revision: 0 }).error, 'twitch_routing_conflict');
  assert.deepEqual(createRouting({ storePath, colorLibrary }).resolve('red').fixtureIds, ['left', 'right']);
  assert.equal(routing.save({ ...state, mode: 'off' }).ok, true);
  assert.equal(routing.resolve('red').error, 'channel_point_lighting_disabled');
  assert.equal(routing.resolveAll().error, 'channel_point_lighting_disabled');
});
test('parser switches take effect without retaining the preceding command modifiers', t => {
  const { parser, routing } = setup(t);
  routing.save({ ...routing.snapshot(), parser: { allowFuzzy: false, allowDescriptors: false, defaultBrightness: 80 } });
  assert.equal(parser.parseTwitchColorDirective('bleu').ok, false);
  assert.equal(parser.parseTwitchColorDirective('light blue').error, 'color_descriptors_disabled');
  assert.equal(parser.parseTwitchColorDirective('red 30%').brightnessPercent, 30);
  assert.equal(parser.parseTwitchColorDirective('red').brightnessPercent, 80);
});
test('StreamElements reward input normalizes color and routes active versus prefixed fixtures', async t => {
  const runtimeDir = fs.mkdtempSync(path.join(os.tmpdir(), 'twitch-widget-program-'));
  const { app, services } = createServer({ runtimeDir, dryRun: true, widgetIntakeToken: 'test-intake-token' });
  const core = services.lightingCore;
  for (const [i, id] of ['left', 'right', 'private'].entries()) core.fixtureRegistry.upsertFixture({ id, brand: 'wiz', ip: `192.0.2.${10 + i}`, twitchEnabled: id !== 'private', engineEnabled: true });
  core.twitchLightRouting.save({ ...core.twitchLightRouting.snapshot(), mode: 'assignments', rules: [rule('active-fixtures', '', ['left', 'private']), rule('desk-rule', 'desk', ['right'])] });
  const server = await new Promise(resolve => { const listener = app.listen(0, '127.0.0.1', () => resolve(listener)); });
  t.after(async () => { await services.lifecycle.stopAll(); await new Promise(resolve => server.close(resolve)); fs.rmSync(runtimeDir, { recursive: true, force: true }); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const send = async (id, input) => {
    const response = await fetch(`${base}/widget/events`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: 'Bearer test-intake-token' }, body: JSON.stringify({ contract: 'widget.events.v2', source: 'streamelements', widgetConfig: { colorRewardId: 'lights' }, eventEnvelope: { detail: { listener: 'redemption-latest', event: { redemption: { id, user_input: input, reward: { id: 'lights' } } } } } }) });
    assert.equal(response.status, 200); return response.json();
  };
  const active = await send('one', 'light red 70%');
  const prefixed = await send('two', 'desk LIGHT BLEU 65%');
  const last = await send('three', 'red');
  assert.deepEqual(active.result.targets, ['left']);
  assert.equal(active.result.skippedTargets, 1);
  assert.equal(active.result.hex, '#ff5959');
  assert.equal(active.result.brightnessPercent, 70);
  assert.deepEqual(active.result.modifiers, { tone: 'light' });
  assert.deepEqual(active.result.wizDelivery.command, { method: 'setPilot', params: { state: true, dimming: 70, r: 255, g: 89, b: 89 } });
  assert.deepEqual(prefixed.result.targets, ['right']);
  assert.equal(prefixed.result.hex, '#5959ff');
  assert.equal(prefixed.result.brightnessPercent, 65);
  assert.equal(prefixed.result.colorMatch, 'blue');
  assert.equal(Boolean(prefixed.result.fuzzy), true);
  assert.equal(last.result.hex, '#ff0000');
  assert.equal(last.result.brightnessPercent, 100);
  assert.deepEqual(last.result.modifiers, {});
  assert.equal((await send('two', 'desk LIGHT BLEU 65%')).duplicate, true);
  const preview = await fetch(`${base}/twitch/lights/preview`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ text: 'light red' }) }).then(response => response.json());
  assert.equal(preview.preview, true); assert.equal(preview.sent, 0); assert.equal(preview.ok, true);
  const direct = await fetch(`${base}/color`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ groupId: 'desk-rule', text: 'blue' }) }).then(response => response.json());
  assert.deepEqual(direct.targets, ['right']);
  assert.equal((await fetch(`${base}/light-groups`)).status, 404);
});
test('legacy lighting groups migrate once into canonical fixture rules', t => {
  const runtimeDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fixture-group-migration-'));
  t.after(() => fs.rmSync(runtimeDir, { recursive: true, force: true }));
  fs.mkdirSync(path.join(runtimeDir, 'fixtures'), { recursive: true });
  fs.writeFileSync(path.join(runtimeDir, 'fixtures', 'light-groups.json'), JSON.stringify({ version: 1, revision: 1, groups: [{ id: 'old-desk', name: 'Desk Pair', fixtureIds: ['left', 'right'] }] }));
  const first = createServer({ runtimeDir, dryRun: true });
  const migrated = first.services.lightingCore.twitchLightRouting.snapshot();
  assert.deepEqual(migrated.rules[0], { id: 'old-desk', name: 'Desk Pair', prefix: 'group_desk_pair', enabled: true, fixtureIds: ['left', 'right'] });
  assert.equal(migrated.mode, 'assignments');
  assert.equal(fs.existsSync(path.join(runtimeDir, 'fixtures', 'light-groups.json')), false);
  assert.equal(fs.existsSync(path.join(runtimeDir, 'fixtures', 'light-groups.json.migrated')), true);
  first.services.lightingCore.twitchLightRouting.save({ ...migrated, rules: [] });
  const second = createServer({ runtimeDir, dryRun: true });
  assert.deepEqual(second.services.lightingCore.twitchLightRouting.snapshot().rules, []);
});
